# create_user.yml
---
- name: Create User and SSH
  hosts: server
  tasks:
    - name: Generate SSH Key
      command: ssh-keygen -t rsa -b 4096 -N '' -f "{{ lookup('env','HOME') }}/.ssh/id_rsa"

    - name: Encrypt SSH Public Key with ansible-vault
      ansible.builtin.command: ansible-vault encrypt "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub" --output "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub.encrypted"
      environment:
        ANSIBLE_VAULT_PASSWORD: "your_vault_password_here"

    - name: Add Encrypted Public Key to Remote Server
      ansible.builtin.copy:
        src: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub.encrypted"
        dest: "/home/user1/.ssh/id_rsa.pub.encrypted"
        owner: user1
        group: user1
        mode: "0644"

    - name: Create User1
      ansible.builtin.user:
        name: user1
        state: present

    - name: Create SSH Directory for User1
      ansible.builtin.file:
        path: "/home/user1/.ssh"
        state: directory
        owner: user1
        group: user1
        mode: "0700"

    - name: Decrypt and Set SSH Public Key for User1
      ansible.builtin.command: ansible-vault decrypt "/home/user1/.ssh/id_rsa.pub.encrypted" --output "/home/user1/.ssh/id_rsa.pub"
      environment:
        ANSIBLE_VAULT_PASSWORD: "your_vault_password_here"

    - name: Add SSH Public Key to Authorized Keys
      ansible.builtin.lineinfile:
        path: "/home/user1/.ssh/authorized_keys"
        line: "{{ lookup('file', '/home/user1/.ssh/id_rsa.pub') }}"
        state: present
        create: yes
        owner: user1
        group: user1
        mode: "0600"
