---
- name: Install and run Docker on app servers
  hosts: app
  become: yes
  tasks:
    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes